---
repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.35.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
