---
collections:
  - name: amazon.aws
    version: 6.5.0
  - name: amazon.cloud
    version: 0.4.0
    type: git
    source: https://github.com/ansible-collections/amazon.cloud.git
  - name: ansible.utils
    version: 2.11.0
  - name: azure.azcollection
    version: 1.18.1
  - name: ansible.controller
    version: 4.4.2
  - name: ansible.windows
    version: 2.1.0
  - name: awx.awx
    version: 23.2.0
  - name: cloud.terraform
    version: 1.1.1
    type: git
    source: https://github.com/ansible-collections/cloud.terraform.git
  - name: community.aws
    version: 6.3.0
  - name: community.digitalocean
    version: 1.24.0
  - name: community.general
    version: 7.4.0
  - name: google.cloud
    version: 1.2.0
  - name: linode.cloud
    version: 0.21.0
  - name: oracle.oci
    version: 4.32.0
  - name: vultr.cloud
    version: 1.10.0
