---
collections:
  - name: amazon.aws
  - name: amazon.cloud
    type: git
    source: https://github.com/ansible-collections/amazon.cloud.git
  - name: ansible.utils
  - name: azure.azcollection
  - name: ansible.controller
  - name: ansible.windows
  - name: awx.awx
  - name: cloud.terraform
    type: git
    source: https://github.com/ansible-collections/cloud.terraform.git
  - name: community.aws
  - name: community.digitalocean
  - name: community.general
  - name: google.cloud
  - name: lab.aws_infrastructure_demo_config
    type: git
    source: https://github.com/ansible-content-lab/aws.infrastructure_config_demos.git
  - name: lab.azure_infrastructure_demo_config
    type: git
    source: https://github.com/ansible-content-lab/azure.infrastructure_config_demos.git
  - name: lab.controller_demo_config
    type: git
    source: https://github.com/ansible-content-lab/aoc.controller_demo_config.git
  - name: linode.cloud
  - name: oracle.oci
  - name: vultr.cloud
