---
collections:
  - name: amazon.aws
    version: 5.4.0
  - name: amazon.cloud
    version: 0.2.0
  - name: ansible.utils
    version: 2.10.2
  - name: azure.azcollection
    version: v1.15.0
    type: git
    source: https://github.com/ansible-collections/azure.git
  - name: ansible.windows
    version: 1.13.0
  - name: awx.awx
    version: 21.12.0
  - name: cloud.terraform
    version: 1.1.1
    type: git
    source: https://github.com/ansible-collections/cloud.terraform.git
  - name: community.aws
    version: 5.4.0
  - name: community.general
    version: 7.0.0
  - name: oracle.oci
    version: 4.22.0
  - name: google.cloud
    version: 1.1.3
  - name: linode.cloud
    version: 0.16.0
  - name: community.digitalocean
    version: 1.23.0
  - name: vultr.cloud
    version: 1.7.1
