---
collections:
  - name: amazon.aws
    version: 6.1.0
  - name: amazon.cloud
    version: 0.4.0
    type: git
    source: https://github.com/ansible-collections/amazon.cloud.git
  - name: ansible.utils
    version: 2.10.3
  - name: azure.azcollection
    version: 1.16.0
  - name: ansible.controller
    version: 4.4.0
  - name: ansible.windows
    version: 2.0.0
  - name: awx.awx
    version: 22.5.0
  - name: cloud.terraform
    version: 1.1.1
    type: git
    source: https://github.com/ansible-collections/cloud.terraform.git
  - name: community.aws
    version: 6.0.0
  - name: community.general
    version: 7.1.0
  - name: oracle.oci
    version: 4.26.0
  - name: google.cloud
    version: 1.2.0
  - name: linode.cloud
    version: 0.16.1
  - name: community.digitalocean
    version: 1.23.0
  - name: vultr.cloud
    version: 1.8.0
