---
collections:
  - name: amazon.aws
    version: 5.1.0
  - name: amazon.cloud
    version: 0.2.0
  - name: ansible.utils
    version: 2.8.0
  - name: azure.azcollection
    version: 1.14.0
  - name: ansible.windows
  - name: awx.awx
    version: 21.10.2
  - name: cloud.terraform
    version: 1.0.0
  - name: community.aws
    version: 5.0.0
  - name: community.general
    version: 6.2.0
  - name: oracle.oci
    version: 4.8.0
  - name: google.cloud
    version: 1.1.2
  - name: linode.cloud
    version: 0.12.1
  - name: community.digitalocean
    version: 1.23.0
  - name: vultr.cloud
    version: 1.6.0
